### ISSUE TITLE
Try to apply Diátaxis

### ISSUE THREAD

**Issue by misohu** [Packeta/api-documentation#4]
Hi first of all I really like the idea going public with something like this. I can see there has been a lot of good work done in this documentation. I just wanted to give small recommendation to take a look a [Diátaxis framework](https://diataxis.fr/). When writing public facing technical documentation like this we (software engineers) tend to fall in lot of "traps" regarding the way how we organise the content. Sometimes we do a lot of assumptions about documentation readers and their technical experience. Based on my experience with open source projects and their documentation I highly recommend checking the Diátaxis as it helps to organise the content. 

Examples of docs which my team wrote with Diátaxis https://charmed-kubeflow.io/docs, https://juju.is/docs/juju

Good luck :)

**Comment by PU-Packeta** [comment]
Hello @misohu, thank you for valuable comment regarding to our new documentation. We will definitely check on your recommendation as well as examples you provided. Have a great day.
